reintegration of test coverage into the CI

diff --git a/.github/workflows/frontend-ci.yml b/.github/workflows/frontend-ci.yml
--- a/.github/workflows/frontend-ci.yml
+++ b/.github/workflows/frontend-ci.yml
@@ -33,27 +33,28 @@ jobs:
       - name: Run build (à activer plus tard)
         run: npm run build
 
-      #- name: Run tests with code coverage
-      #  run: |
-       #   npm run test -- --watch=false --browsers=ChromeHeadless --code-coverage
+      - name: Run tests with code coverage
+        run: |
+          npm run test -- --watch=false --browsers=ChromeHeadless --code-coverage
 
-#      - name: Check code coverage ≥ 80%
- #       run: |
-  #        coverage_file=coverage/index.html
-   #       percent=$(grep -A3 "Statements" $coverage_file | grep -Po '[0-9]+(?=%)' | head -1)
-#      if [[ -z "$percent" ]]; then
- #           echo "Impossible de lire la couverture depuis le fichier HTML."
-  #          exit 1
-   #       fi
+      - name: Check code coverage ≥ 80%
+        run: |
+          coverage_file=coverage/index.html
+          percent=$(grep -A3 "Statements" $coverage_file | grep -Po '[0-9]+(?=%)' | head -1)
 
-    #      echo "Coverage from HTML = $percent%"
+          if [[ -z "$percent" ]]; then
+            echo "Impossible de lire la couverture depuis le fichier HTML."
+            exit 1
+          fi
 
-     #     if [ "$percent" -lt 80 ]; then
-      #      echo "Code coverage ($percent%) is below 80%. Failing the job."
-       #     exit 1
-        #  else
-         #   echo "Code coverage is sufficient ($percent%)."
-          #fi
+          echo "Coverage from HTML = $percent%"
+
+          if [ "$percent" -lt 80 ]; then
+            echo "Code coverage ($percent%) is below 80%. Failing the job."
+            exit 1
+          else
+            echo "Code coverage is sufficient ($percent%)."
+          fi
 
       - name: SonarCloud analysis (non-blocking)
         continue-on-error: true
